#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x71C636695B147849 (dict-upload@aspell.net)
#
Name     : aspell-pt_BR
Version  : 20131030.12.0
Release  : 5
URL      : https://mirrors.kernel.org/gnu/aspell/dict/pt_BR/aspell6-pt_BR-20131030-12-0.tar.bz2
Source0  : https://mirrors.kernel.org/gnu/aspell/dict/pt_BR/aspell6-pt_BR-20131030-12-0.tar.bz2
Source1 : https://mirrors.kernel.org/gnu/aspell/dict/pt_BR/aspell6-pt_BR-20131030-12-0.tar.bz2.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: aspell-pt_BR-license = %{version}-%{release}
BuildRequires : aspell
Patch1: 0001-Allow-unrecognized-options.patch

%description
GNU Aspell 0.60 Brazilian Portuguese (Português do Brasil) Dictionary Package
Version 20131030-12-0
2019-07-23
Maintained By:
Kevin Atkinson <kevina at gnu org>
Agustin Martin Domingo <agmartin at debian org>
Wordlist URL: https://packages.debian.org/testing/aspell-pt-br
Source URL: http://pt-br.libreoffice.org/projetos/projeto-vero-verificador-ortografico

%package license
Summary: license components for the aspell-pt_BR package.
Group: Default

%description license
license components for the aspell-pt_BR package.


%prep
%setup -q -n aspell6-pt_BR-20131030-12-0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1564176339
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1564176339
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/aspell-pt_BR
cp Copyright %{buildroot}/usr/share/package-licenses/aspell-pt_BR/Copyright
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/aspell-0.60/br-abnt2.kbd
/usr/lib64/aspell-0.60/brasileiro.alias
/usr/lib64/aspell-0.60/brazilian.alias
/usr/lib64/aspell-0.60/pt_BR.dat
/usr/lib64/aspell-0.60/pt_BR.multi
/usr/lib64/aspell-0.60/pt_BR.rws
/usr/lib64/aspell-0.60/pt_BR_affix.dat

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/aspell-pt_BR/Copyright
