#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : aspell-pt_BR
Version  : 20090702.0
Release  : 2
URL      : https://mirrors.ocf.berkeley.edu/gnu/aspell/dict/pt_BR/aspell6-pt_BR-20090702-0.tar.bz2
Source0  : https://mirrors.ocf.berkeley.edu/gnu/aspell/dict/pt_BR/aspell6-pt_BR-20090702-0.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
BuildRequires : aspell
Patch1: 0001-Allow-unrecognized-options.patch

%description
GNU Aspell 0.60 Brazilian Portuguese (PortuguÃªs do Brasil) Dictionary Package
Version 20090702-0
2009-07-05
Maintained By:
Leonardo Ferreira Fontenelle <leonardof at gnome org>
Original Word List Also By:
Raimundo Santos Moura <raimundomoura at openoffice org>
Source URL: http://www.broffice.org/verortografico
This word list is considered both complete and accurate.

%prep
%setup -q -n aspell6-pt_BR-20090702-0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534206722
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1534206722
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/aspell-0.60/br-abnt2.kbd
/usr/lib64/aspell-0.60/pt_BR.dat
/usr/lib64/aspell-0.60/pt_BR.multi
/usr/lib64/aspell-0.60/pt_BR.rws
/usr/lib64/aspell-0.60/pt_BR_affix.dat
