#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x71C636695B147849 (dict-upload@aspell.net)
#
Name     : aspell-pt_BR
Version  : 20090702.0
Release  : 3
URL      : https://mirrors.kernel.org/gnu/aspell/dict/pt_BR/aspell6-pt_BR-20090702-0.tar.bz2
Source0  : https://mirrors.kernel.org/gnu/aspell/dict/pt_BR/aspell6-pt_BR-20090702-0.tar.bz2
Source99 : https://mirrors.kernel.org/gnu/aspell/dict/pt_BR/aspell6-pt_BR-20090702-0.tar.bz2.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: aspell-pt_BR-license = %{version}-%{release}
BuildRequires : aspell
Patch1: 0001-Allow-unrecognized-options.patch

%description
GNU Aspell 0.60 Brazilian Portuguese (PortuguÃªs do Brasil) Dictionary Package
Version 20090702-0
2009-07-05
Maintained By:
Leonardo Ferreira Fontenelle <leonardof at gnome org>
Original Word List Also By:
Raimundo Santos Moura <raimundomoura at openoffice org>
Source URL: http://www.broffice.org/verortografico
This word list is considered both complete and accurate.

%package license
Summary: license components for the aspell-pt_BR package.
Group: Default

%description license
license components for the aspell-pt_BR package.


%prep
%setup -q -n aspell6-pt_BR-20090702-0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1545336552
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1545336552
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/aspell-pt_BR
cp COPYING %{buildroot}/usr/share/package-licenses/aspell-pt_BR/COPYING
cp Copyright %{buildroot}/usr/share/package-licenses/aspell-pt_BR/Copyright
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/aspell-0.60/br-abnt2.kbd
/usr/lib64/aspell-0.60/pt_BR.dat
/usr/lib64/aspell-0.60/pt_BR.multi
/usr/lib64/aspell-0.60/pt_BR.rws
/usr/lib64/aspell-0.60/pt_BR_affix.dat

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/aspell-pt_BR/COPYING
/usr/share/package-licenses/aspell-pt_BR/Copyright
